### ISSUE TITLE
standalone C UDP writer/reader

### ISSUE THREAD

**Issue by evanmayer** [tim-balloon/TIMflight#2]
## Task

Write two small programs in C to build skills and useful code for when we have to write and test code to talk to detector control boards later on.

* Write a UDP writer program:
    * Specify a place to spew packets: a loopback IP address and port
    * Populate a struct according to UDP
    * Send some data - first try chars or ints (easy), then try sending floats (harder)
    
* Write a UDP listener program:
    * Receive packets on a port
    * unpack the received data
    * print or do something to show it's working (maybe even write a unit test to show this?)
    
* Write a .md or .txt file describing how to build and run them so anybody can see how it should work.

## Acceptance

Complete when both programs compile and run and there's proof that data is communicated successfully.

Put the example code and any files you need to build in a dir called `sandbox` for now, to keep it separate from other code until it has a home as part of a test suite. Work in your own development branch (make a new one), make any commits there, and [open a pull request to the `master` branch to complete this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when done. 
    
## Context

We expect the flight computer running `mcp` to receive [UDP](https://en.wikipedia.org/wiki/User_Datagram_Protocol) packets containing detector data from the Xilinx radio frequency system-on-chip (RFSoC) boards. They get shuffled to telemetry to get them off the balloon as well as recorded locally to hard disks for recovery and post-flight reconstruction after landing.

I have found this explainer on network programming useful for understanding what UDP is all about:
[Beej's Guide to Network Programming](http://beej.us/guide/bgnet/html/index-wide.html)
It's good because many of the examples are written in C.

Once you know what function calls are used to get things done, you might also be able to look at code in the repo for examples, as things are already talking using UDP.

**Comment by brendal4** [comment]
Receive data on a socket: http://beej.us/guide/bgnet/html/index-wide.html#recvman
Send data over a socket: http://beej.us/guide/bgnet/html/index-wide.html#sendman

**Comment by brendal4** [comment]
Loopback IP is 127.0.0.1, i.e. any message is looped through the network card and comes back

**Comment by brendal4** [comment]
Unit testing in C: https://libcheck.github.io/check/

**Comment by brendal4** [comment]
Scripts live [here](https://github.com/brendal4/my_projects/tree/main/UDP_writer_listener) for now

**Comment by evanmayer** [comment]
Closing as sufficient C UDP knowledge/testing capability has been gained.
