### ISSUE TITLE
[EVTM] Initial EVTM implementation

### ISSUE THREAD

**Issue by evanmayer** [tim-balloon/TIMflight#60]
## Task

In order to send some telemetry (TM) data using the Columbia Scientific Ballooning Facility (CSBF) Ethernet Via Telemetry (EVTM) system, we must replace line of sight biphase and Tracking and Data Relay Satellite System (TDRSS) TM senders with universal datagram protocol (UDP) multicast senders. 

## Acceptance

New thread instantiated in `mcp` alongside `pilot` that sends data to a UDP multicast address in the CSBF-accepted range for LOS comms. Refer to CSBF "EVTM Details" and "EVTM Simulated Testing" PDFs. To limit scope, UDP multicast packet sending may be verified by reception via Wireshark or another computer running `iperf`, `tcpdump`, or a bespoke listener, and does not need to be ground support equipment. Do not remove the any existing senders yet - we will wait until ground support receiver functionality has been tested with EVTM.

Appropriate unit tests are mandatory for acceptance of this development work.

## Details

We can begin this task by keeping existing components, creating a new TM sender that uses UDP multicast alongside the existing ones. A UDP (but not multicast) sender exists in the form of the Iridium Pilot sender (`pilot` in code). Extend the `BitSender` code to support multicast packet sending, if necessary - do not re-implement any functionality in `BitSender`. 

[EVTM Details.pdf](https://github.com/tim-balloon/TIMflight/files/12675696/EVTM.Details.pdf)
[EVTM Simulated Testing.A.pdf](https://github.com/tim-balloon/TIMflight/files/12675697/EVTM.Simulated.Testing.A.pdf)

**Comment by shubhagrawal30** [comment]
Notes: https://github.com/tim-balloon/tim-logs/tree/main/telemetry
